### ISSUE TITLE
It would be better to not have to add @Column everywhere and to treat capitalized name as spaced one automatically

### ISSUE THREAD

**Issue by monkawa** [deblockt/cucumber-datatable-to-bean-mapping#19]
Most cucumber entities i write are dedicated only to cucumber and with properly named field.
@Column should not be mandatory and capitalized named shouldn't have to be rewritten if no siginificant differences.

It would be better to be able to write the following 

```java   
 @DataTableWithHeader 
    record EmailToSend(
            @Column(value = "email")
            String email,
            @Column(value = "from")
            String name from,
            @Column(value = "the last name")
            String theLastName
    ) {}
```
as
```java   
 @DataTableWithHeader 
    record EmailToSend(
            String email,
            String name from,
            String theLastName
    ) {}
```

**Comment by deblockt** [comment]
Starting from version 1.0.4, the `value` property within the `Column` annotation is no longer mandatory. The column name is now derived from the property name itself. For instance, if you have a property named `theLastName`, you can use either `theLastName` or `the last name` as the column name.

I am currently in the process of reworking some code to eliminate the necessity of using the `@Column` annotation. This effort is still a work in progress.

**Comment by deblockt** [comment]
The version [1.1.0](https://github.com/deblockt/cucumber-datatable-to-bean-mapping/releases/tag/1.1.0) contains new configuration entry point the be able to support this type of definition 
``` java 
 @DataTableWithHeader 
    record EmailToSend(
            String email,
            String name from,
            String theLastName
    ) {}
```
